// generated by "sampctl package init"
#include <a_samp>

#include "zones.inc"

main() 
{
	new Zone:zoneId, zoneName[MAX_ZONE_NAME + 1];
	GetPlayer2DZone(0, zoneId);
	GetPlayer3DZone(0, zoneId);
	Get2DZone(zoneId, 0.0, 0.0);
	Get3DZone(zoneId, 0.0, 0.0, 0.0);
	GetZoneName(zoneId, zoneName, sizeof zoneName);

	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

public OnGameModeInit()
{
	AddPlayerClass(101, 0.0, 0.0, 5.0, random(360), 24, 9999, 25, 9999, 31, 9999);
	AddStaticVehicle(522, 10.0, 10.0, 5.0, random(360), 5, 6);
}

public OnGameModeExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	SetPlayerSkillLevel(playerid, 24, 999);
	SetPlayerSkillLevel(playerid, 25, 999);
	SetPlayerSkillLevel(playerid, 31, 999);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(isnull(cmdtext))
	{
		return 0;
	}
	if(strcmp(cmdtext, "/2dzone") == 0)
	{
		new Zone:zoneId;
		if(GetPlayer2DZone(playerid, zoneId))
		{
			new zoneName[MAX_ZONE_NAME + 1];
			GetZoneName(zoneId, zoneName, sizeof zoneName);
			SendClientMessage(playerid, -1, zoneName);
		}
		return 1;
	}
	if(strcmp(cmdtext, "/3dzone") == 0)
	{
		new Zone:zoneId;
		if(GetPlayer3DZone(playerid, zoneId))
		{
			new zoneName[MAX_ZONE_NAME + 1];
			GetZoneName(zoneId, zoneName, sizeof zoneName);
			SendClientMessage(playerid, -1, zoneName);
		}
		return 1;
	}
	if(strcmp(cmdtext, "/2dzonepos") == 0)
	{
		new Float:x, Float:y, Float:z;
		GetPlayerPos(playerid, x, y, z);

		new Zone:zoneId;
		if(Get2DZone(zoneId, x, y))
		{
			new zoneName[MAX_ZONE_NAME + 1];
			GetZoneName(zoneId, zoneName, sizeof zoneName);
			SendClientMessage(playerid, -1, zoneName);
		}
		return 1;
	}
	if(strcmp(cmdtext, "/3dzonepos") == 0)
	{
		new Float:x, Float:y, Float:z;
		GetPlayerPos(playerid, x, y, z);

		new Zone:zoneId;
		if(Get3DZone(zoneId, x, y, z))
		{
			new zoneName[MAX_ZONE_NAME + 1];
			GetZoneName(zoneId, zoneName, sizeof zoneName);
			SendClientMessage(playerid, -1, zoneName);
		}
		return 1;
	}
	return 0;
}

public OnPlayerEnterZone(playerid, Zone:zoneid, bool:main)
{
	new zoneName[MAX_ZONE_NAME + 1], message[128];
	GetZoneName(zoneid, zoneName, sizeof zoneName);
	format(message, sizeof message, "You have entered: %s - Main: %d", zoneName, main);
	SendClientMessage(playerid, -1, message);
}

public OnPlayerLeaveZone(playerid, Zone:zoneid, bool:main)
{
	new zoneName[MAX_ZONE_NAME + 1], message[128];
	GetZoneName(zoneid, zoneName, sizeof zoneName);
	format(message, sizeof message, "You have left: %s - Main: %d", zoneName, main);
	SendClientMessage(playerid, -1, message);
}

